# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


# Site Settings
locale                   : "en-US"
title                    : "Title"
title_separator          : "-"
name                     : &name "your name"
description              : &description "Website description"
url                      : http://blog.com # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
# repository               : ""
# teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
# words_per_minute         : 200



# SEO Related
google_site_verification : ""
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :



# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-2011187-3"



# Site Author
author:
  name             : *name
  avatar           :
  bio              : "Just another boring, tattooed, time traveling, designer."
  location         :
  email            :
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          :



# Reading Files
include:
  - _pages
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"



# Conversion
markdown: kramdown
# highlighter: rouge
# lsi: false
# excerpt_separator: "\n\n"
# incremental: false



# Markdown Processing
# kramdown:
#   input: GFM
#   hard_wrap: false
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   smart_quotes: lsquo,rsquo,ldquo,rdquo
#   enable_coderay: false


# Collectsions
collections:
  projects:
    output: true
    permalink: /:collection/:path/



# Defaults

defaults:

  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: default

  # Projects
  - scope:
      path: _posts
      type: posts
    values:
      layout: project



# Jakyll assets
assets:
  # debug: false
  # css_compressor: sass
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
  autoprefixer:
    browsers: ["last 2 versions","> 5%","IE 9"]



# Plugins
gems:
  - jekyll-assets



# HTML Compression
# - http://jch.penibelst.de/
# compress_html:
#   clippings: all
#   ignore:
#     envs: development



# Server Config options
livereload: true     # You no longer need to include --livereload
# reload_port: 5678    # If you don't want to use the default port
